### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by HEmile** [AntreasAntoniou/kubejobs#6]
Hi there,

I was trying out the first script in the README. This fails at importing `KubernetesJob` as it is not exposed by the top package. The correct current import is `from kubejobs.jobs import KubernetesJob`.

After that, I'm getting the following error:
```
Traceback (most recent call last):
  File "/home/eidf029/eidf029/evankri-infk8s/python_pod.py", line 4, in <module>
    job = KubernetesJob(
          ^^^^^^^^^^^^^^
  File "/home/eidf029/eidf029/evankri-infk8s/miniconda3/lib/python3.11/site-packages/kubejobs/jobs.py", line 125, in __init__
    else MAX_CPU // (MAX_GPU - gpu_limit + 1)
                     ~~~~~~~~^~~~~~~~~~~
TypeError: unsupported operand type(s) for -: 'int' and 'NoneType'
```

**Comment by HEmile** [comment]
To fix that error, ensure you give a value go `gpu_limit` and to `cpu_request`.

**Comment by AntreasAntoniou** [comment]
I believe I fixed this. Will close. Let me know if you do not think this is solved.
